### ISSUE TITLE
(Multi)Login to conan remotes feature ignores "deselected" remotes

### ISSUE THREAD

**Issue by christophh-tt** [goszpeti/conan_app_launcher#167]
**Describe the bug**
Login to conan remotes feature ignores _deselected_ remotes and login to **all** listed remotes. Nevertheless the remote are selected or not in the dialog. No login to the different remotes did happen before ( user for each remote was anonymous or ... what ever ).

**Expected behavior**
The (Multi)Login Feature should handle selected and deslected remotes properly. The login shoud not happen for deselected remotes.

**Desktop (please complete the following information):**
 - OS: Windows10

**Additional context**
* conan_app_launcher version: 1.4.2

**Comment by goszpeti** [comment]
Disabled remotes are now deselected per default.
The selection flags will also be honored when clicking on OK.
